### ISSUE TITLE
Docker image tags

### ISSUE THREAD

**Issue by NicoLaval** [zazukoians/qlever-tests#4]
Is it possible to improve GHA workflow to publish latest and tagged images?

**Comment by ludovicm67** [comment]
Thank you @NicoLaval for the issue!

It should already be the case.
`latest` tag will refer to the latest SemVer tag ; right now, none has been published.
I will see to publish a version which is tagged as SemVer, so that it would be easier to refer to it.

I will keep this issue open until a SemVer release is done.
